version: "3.8"
services:
  men-cave-frontend-application:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start 
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 4200:4200
    volumes:
      - .:/app 
      - /app/node_modules

  men-cave-test-coverage:
    build: .
    command: npm run test-headless
    volumes:
      - .:/app