version: "3.8"
services:
  front_end:
    container_name: men_cave
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start 
    ports:
      - 4200:4200
    volumes:
      - .:/app 
      - /app/node_modules 