ARG NODE_VERSION=20.18.1

FROM node:${NODE_VERSION}-bookworm-slim

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true

COPY package.json package-lock.json ./
RUN npm ci

COPY . ./

EXPOSE 4200

CMD ["npm", "start"]
